### ISSUE TITLE
No access to commands from previous buildpacks

### ISSUE THREAD

**Issue by akkie** [heroku/heroku-buildpack-scala#102]
Hi,

I try to deploy a [Play Yeoman][1] application to heroku. I use the [heroku-buildpack-multi][2] and my .buildbacks file looks as follows:

    https://github.com/heroku/heroku-buildpack-ruby.git
    https://github.com/heroku/heroku-buildpack-nodejs.git
    https://github.com/heroku/heroku-buildpack-scala.git

The first two buildpacks will be executed successful. The third buildpack fails with the message:

    Will run: [grunt, --gruntfile=Gruntfile.js] in /tmp/scala_buildpack_build_dir/ui
       java.io.IOException: Cannot run program "grunt" (in directory "/tmp/scala_buildpack_build_dir/ui"): error=2, No such file or directory

In my project there exists a package.json which looks as follows:

    {
      "name": "play-silhouette-angular-seed",
      "version": "0.0.0",
      "dependencies": {
        "grunt-cli": "~0.1.13",
        "grunt": "~0.4.5",
        "bower": "~1.3.12",
        "yo":  "~1.3.3"
      },
      "engines": {
        "node": "0.10.x"
      }
    }

All the node components will be installed during the build process. If I remove the scala buildpack then I can see the node_modules folder. The bin folder inside the node_modules folder is also in the path and I can run the grunt command from the bash.

The problem is now that the scala buildpack has no access to the grunt command. But why?

Best regards,
Christian

  [1]: https://github.com/tuplejump/play-yeoman
  [2]: https://github.com/heroku/heroku-buildpack-multi

**Comment by jkutner** [comment]
I think you might need to move grunt into devDependencies in your package.json. A common setup for some apps I've seen is this:

```json
{
  "name": "java-grunt",
  "dependencies": {
    "grunt-cli": "0.1.13"
  },
  "devDependencies": {
    "grunt": "~0.4.5",
    "grunt-contrib-uglify": "~0.5.0"
  }
}
```

That's just a guess though. I'll keep looking into it.

If you have a simple OSS project or some source code that reproduces this, it would be really helpful for me. Thanks.

**Comment by akkie** [comment]
The node buildpack runs with `NPM_CONFIG_PRODUCTION=true` and therefore no dev dependencies will be installed on the system. But it may be possible that grunt-cli is the only package needed to start the application. I'll test this later if I'm able to deploy the application to heroku.

You can use the following project to reproduce the issue.
https://github.com/mohiva/play-silhouette-angular-seed

**Comment by jkutner** [comment]
I was able to reproduce. I know what's going one, but it might take a bit get a good solution into the buildpack. I'll update soon. Thanks for reporting this!

**Comment by akkie** [comment]
Thanks for looking into this. I'll wait for your reply.

**Comment by jkutner** [comment]
I've updated the master branch such that the grunt command should work now. But I end up with this:

```
remote:        Will run: [grunt, --gruntfile=Gruntfile.js] in /tmp/scala_buildpack_build_dir/ui
remote:        Loading "Gruntfile.js" tasks...ERROR
remote:        >> Error: Cannot find module 'load-grunt-tasks'
remote:        Warning: Task "default" not found. Use --force to continue.
remote:        
remote:        Aborted due to warnings.
```

I've tried getting the dependencies in `ui/package.json` installed, but when I try to load them in the nodejs buildpack, they are skipped because they are devDependencies (as you mentioned earlier).

Any suggestions?

**Comment by akkie** [comment]
I've got it partially working. I've disabled production mode for npm with: 
```bash
heroku config:set NPM_CONFIG_PRODUCTION=false
```

Then I've updated my `package.json` to install all dependencies in the `ui` directory:

```js
{
  "name": "play-silhouette-angular-seed",
  "version": "0.0.0",
  "dependencies": {
    "grunt-cli": "~0.1.13",
    "bower": "~1.3.12"
  },
  "devDependencies": {
    "yo":  "~1.3.3"
  },
  "engines": {
    "node": "0.10.x"
  },
  "scripts": {
    "postinstall": "cd ui && npm install && bower install"
  }
}
```
Now grunt runs, but It seems that `compass` and `sass` are not available during build. I get the following error:
```
Running "concurrent:test" (concurrent) task
           
           Running "compass:dist" (compass) task
           Warning: ↑ Used --force, continuing.
           
           Running "compass:server" (compass) task
           Warning: ↑ Used --force, continuing.
           
           Done, but with warnings.
           
           
           Execution Time (2015-01-16 23:21:50 UTC)
           loading tasks     5ms  ▇ 1%
           compass:dist    387ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 78%
           compass:server  101ms  ▇▇▇▇▇▇▇▇▇▇ 20%
           Total 494ms
```

and then later:
```
Running "cssmin:generated" (cssmin) task
       File dist/styles/vendor.css created.
       >> Destination not written because minified CSS was empty.
```

The application runs then but the `sass` files gets not compiled to `css`. If I run the bash and execute grunt in the `ui` directory then the build runs without any error and the `sass` files will be compiled into `css`.

**Comment by akkie** [comment]
You can find the current example under the following URL:
https://github.com/akkie/play-silhouette-angular-seed

**Comment by jkutner** [comment]
When I ran it, I saw this:

```
remote:        Running "concurrent:test" (concurrent) task
remote:            
remote:            Running "compass:dist" (compass) task
remote:            directory .tmp/styles
remote:                write .tmp/styles/main.css (3.444s)
remote:            
remote:            Running "compass:server" (compass) task
remote:            
remote:            Done, without errors.
remote:            
remote:            
remote:            Execution Time (2015-01-17 01:44:34 UTC)
remote:            compass:dist    7.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 60%
remote:            compass:server  5.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 40%
remote:            Total 12.9s
...
remote:        Running "concurrent:dist" (concurrent) task
remote:            
remote:            Running "imagemin:dist" (imagemin) task
remote:            Minified 0 images (saved 0 B)
remote:            
remote:            Done, without errors.
remote:            
remote:            
remote:            Execution Time (2015-01-17 01:45:16 UTC)
remote:            loading tasks  230ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 94%
remote:            imagemin:dist   14ms  ▇▇▇ 6%
remote:            Total 245ms
remote:                
remote:            Running "svgmin:dist" (svgmin) task
remote:            
remote:            Done, without errors.
remote:            
remote:            
remote:            Execution Time (2015-01-17 01:45:16 UTC)
remote:            loading tasks  229ms  ▇▇▇▇▇ 10%
remote:            svgmin:dist       2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 90%
remote:            Total 2.2s
remote:                
remote:            Running "compass:dist" (compass) task
remote:            directory .tmp/styles
remote:                write .tmp/styles/main.css (2.549s)
remote:            
remote:            Done, without errors.
remote:            
remote:            
remote:            Execution Time (2015-01-17 01:45:16 UTC)
remote:            loading tasks  217ms  ▇▇ 2%
remote:            compass:dist    9.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
remote:            Total 9.5s
...
remote:        Running "cssmin:generated" (cssmin) task
remote:        File dist/styles/vendor.css created.
remote:        File dist/styles/main.css created. 
```

And it actually looks like the whole thing completed successfully. Did you change anything in the play-silhouette-angular-seed?

**Comment by akkie** [comment]
This is strange! If I deploy the application through the toolbelt then it fails with the above errors. If I deploy the app with your button then it works as expected.

Any suggestions?

**Comment by jkutner** [comment]
That concerns me. There's nothing fundamentally different between the button and the toolbelt actually. My toolbelt is 3.23.3. You might try running `heroku update`. I think your toolbelt defaults to using Git deployment over ssh, and the new version uses https. But I can't think of why that would matter.

This is a long and complicate build process though. I wonder if the [sbt-heroku plugin](https://github.com/heroku/sbt-heroku) is a better solution. It packages up the artifacts under the `target` directory and sends them to Heroku (skipping the buildpack process).

Anyways, I'm glad to help with this, so feel free to ask questions if you see anything weird.

**Comment by akkie** [comment]
I'll test this later. Thanks for your help on this issue.
