### ISSUE TITLE
cannot download sbt

### ISSUE THREAD

**Issue by OlegYch** [heroku/heroku-buildpack-scala#104]
```
remote:        Downloading sbt launcher for 0.13.9-M1:        
remote:          From  http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.9-M1/sbt-launch.jar        
remote:            To  /tmp/scala_buildpack_build_dir/.sbt_home/launchers/0.13.9-M1/sbt-launch.jar        
remote:        Download failed. Obtain the jar manually and place it at /tmp/scala_buildpack_build_dir/.sbt_home/launchers/0.13.9-M1/sbt-launch.jar        
remote: 
remote:  !     ERROR: Failed to run sbt!        
remote:        We're sorry this build is failing! If you can't find the issue in application        
remote:        code, please submit a ticket so we can help: https://help.heroku.com        
remote:        You can also try reverting to our legacy Scala buildpack:        
remote:        $ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-scala#legacy        
remote:                
remote:        Thanks,        
remote:        Heroku        
remote: 
remote: 
remote:  !     Push rejected, failed to compile Scala app        
```
it appears that your launcher uses wrong repository, it should be using repo.typesafe.com afaik
also note that 'heroku buildpacks' ' is not a heroku command.'
btw is there a way to use a launcher from my the project repo?

**Comment by jkutner** [comment]
We have not yet added support for sbt 0.13.9-M1. I'll see if I can update for that in the next day or so. In the meantime, please use sbt 0.13.8.

The `heroku buildpacks` command should work. Are you getting an error when you run it?

**Comment by OlegYch** [comment]
my bad, i had old heroku client version
as for sbt version, you shouldn't need any special support
but if you're using some custom launcher i suspect you need to update its config as typesafe repos have recently been moved

**Comment by jkutner** [comment]
Here's the update: https://github.com/heroku/heroku-buildpack-scala/commit/098a02c90603c9f1ee655e62dab356127a11e720

If you'd like to use this immediately (with 0.13.9-M1) you can run:

```
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-scala
```

I have to run some most complete testing before releasing it as the default buildpack.

**Comment by OlegYch** [comment]
On 7/2/2015 1:29 AM, Joe Kutner wrote:
>
> Here's the update: 098a02c 
> <https://github.com/heroku/heroku-buildpack-scala/commit/098a02c90603c9f1ee655e62dab356127a11e720>
>
> If you'd like to use this immediately (with 0.13.9-M1) you can run:
>
> |heroku buildpacks:set https://github.com/heroku/heroku-buildpack-scala |
>
> I have to run some most complete testing before releasing it as the 
> default buildpack.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/heroku/heroku-buildpack-scala/issues/104#issuecomment-117841509>.
>
Thanks, that works.

**Comment by jkutner** [comment]
This was released in v61. forgot to update this ticket.
