### ISSUE TITLE
Play 2.4 application with disabled Play layout causes the slug size to exceed the maximum

### ISSUE THREAD

**Issue by martijnblankestijn** [heroku/heroku-buildpack-scala#108]
In heroku-buildpack-scala/lib/common.sh the detection of the project is a Play-2.x application is done as follows:

```
_has_playConfig() {
  local ctxDir=$1
  test -e $ctxDir/conf/application.conf
}
```

But what if I want to use the default SBT layout? What if I use
```
lazy val root = (project in file("."))
  .enablePlugins(PlayScala)
  .disablePlugins(PlayLayoutPlugin)
```

This means that my application.conf is in the directory ```src/main/resources``` and not in ```conf```.
And this has as a consequence that my slugsize on Heroku is getting to big and it will not build.

**Comment by jkutner** [comment]
@martijnblankestijn are you also not using sbt-native-packager? If you're using Play 2.2 or earlier this may be the case.

**Comment by jkutner** [comment]
Oh nevermind. that's irrelevant

**Comment by martijnblankestijn** [comment]
I use Play 2.4.4, source of the project is at https://github.com/martijnblankestijn/play-2.4-macwire

**Comment by jkutner** [comment]
I'd like to detect `.disablePlugins(PlayLayoutPlugin)`, but i think that could be in just about any `.sbt` file (or even `.scala` file). 

Are there other types of apps (non-Play) that could have a `src/main/resources/application.conf`?

**Comment by martijnblankestijn** [comment]
Yes, there are. The application.conf is described at [here](https://github.com/typesafehub/config), the configuration library of TypeSafe. By default it is also used by [Akka](http://doc.akka.io/docs/akka/snapshot/general/configuration.html).

Is a possibility to activate it explicitly an option?

**Comment by jkutner** [comment]
Yea, we can definitely add an explicit option (probably a good idea regardless), but I'd also like to try and add something that will "just work" for anyone who might run into this in the future. I'm going to make a branch.

**Comment by martijnblankestijn** [comment]
And the name application.conf is just the default for the play-framework. It is however also configurable.

The current implementation uses the environment variable PLAY_CONF_FILE for that.

**Comment by martijnblankestijn** [comment]
I will be following the branch. Thanks for the ultra-quick response!

**Comment by jkutner** [comment]
I've created an [is_play branch](https://github.com/heroku/heroku-buildpack-scala/tree/is_play), which you can test by setting your buildpack like this:

```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-scala#is_play
```

Here's the [diff for the is_play branch](https://github.com/heroku/heroku-buildpack-scala/compare/is_play). It should work for you but I'm not happy with it yet. It could detect an app that has the Play plugin commented out. In any event, it does use the `$IS_PLAY_APP` env var to force detection.

The reason this is difficult is that we can't ask SBT for this information because it will cause it to run dependency resolution or do other things, which can add a long time to the build.

I'll keep working it.

**Comment by jkutner** [comment]
@martijnblankestijn ah, is PLAY_CONF_FILE specific to your app, or is it a convention in Play?

**Comment by martijnblankestijn** [comment]
It is a convention of play I think, searched on github and discovered [77](https://github.com/search?q=PLAY_CONF_FILE&ref=searchresults&type=Code&utf8=%E2%9C%93) entries.

Cannot find the original source for this convention, however
.

**Comment by jkutner** [comment]
Cool. seems reasonable to keep it then. I will work on this branch a bit more, but we can't merge it until after the holidays. I'll update this issue when I do.

**Comment by martijnblankestijn** [comment]
Solution with IS_PLAY_APP works for me. It makes it possible to whatever layout you choose for the application to let Heroku treat it as a Play 2 application.

However I understand your desire to make it work out of the box for users that follow the default conventions,.

As for now: thanks for the quick response and happy Holidays!

**Comment by jkutner** [comment]
This has been released as part of the standard buildpack. Docs to come
