### ISSUE TITLE
support sbt-coursier

### ISSUE THREAD

**Issue by OlegYch** [heroku/heroku-buildpack-scala#114]
https://github.com/alexarchambault/coursier/ - a faster dependency engine pluggable into sbt
this probably means just adding caching for ~/.coursier

**Comment by jkutner** [comment]
This looks like a good idea. I'll will investigate after the holidays.

If you have a sample app prepared (and on Github) that would be a great help.

**Comment by jkutner** [comment]
I've created the branch [coursier](https://github.com/heroku/heroku-buildpack-scala/tree/coursier) to work on this. Can test it by running:

```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-scala#coursier
```

And then redeploying? Thanks.

**Comment by OlegYch** [comment]
thanks, it works!
