### ISSUE TITLE
Commented out version of SBT is detected

### ISSUE THREAD

**Issue by jsimone** [heroku/heroku-buildpack-scala#30]
From a support ticket:

"Was getting a deployment error when deploying a Play Framework 2.0.4 app as follows:

-----> Heroku receiving push 
-----> Play 2.0 - Scala app detected 
! Error, you have defined an unsupported sbt.version in project/build.properties 
! You must use a release verison of sbt, sbt.version=0.11.0 or greater 
! Heroku push rejected, failed to compile Play 2.0 - scala app

my project/build.properties file was as follows:
# sbt.version=0.12.0

sbt.version=0.11.3

when I removed the 'commented' line, it got past the error. Something is probably parsing commented lines to determine sbt.version, becoming confused, and failing the deploy because of a commented line."

**Comment by Malax** [comment]
This has been fixed.
