### ISSUE TITLE
Require.js compilation is slow on Heroku

### ISSUE THREAD

**Issue by jsimone** [heroku/heroku-buildpack-scala#45]
Require.js compilation is slow and often causes build timeouts. It's been observed that build which are fast enough locally can take much longer when building on Heroku.

**Comment by jkutner** [comment]
This is best solved by using Node.js to perform the compilation instead of the default Trireme (which runs on the JVM). The process is described [in this DevCenter article](https://devcenter.heroku.com/articles/using-node-js-to-perform-javascript-optimization-for-play-and-scala-applications).
