### ISSUE TITLE
Deployment to heroku error

### ISSUE THREAD

**Issue by pquarme** [heroku/heroku-buildpack-scala#79]
I get this error when deploying my play app to heroku

[info] Set current project to scala_buildpack_build_dir (in build file:/tmp/scala_buildpack_build_dir/)
       [info] Updating {file:/tmp/scala_buildpack_build_dir/}scala_buildpack_build_dir...
       [info] Resolving org.scala-lang#scala-library;2.10.4 ...
       [info] Resolving org.scala-lang#scala-compiler;2.10.4 ...
       [info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
       [info] Resolving org.scala-lang#jline;2.10.4 ...
       [info] Resolving org.fusesource.jansi#jansi;1.4 ...
       [info] Done updating.
       [success] Total time: 0 s, completed Aug 4, 2014 9:15:25 PM
       [error] Not a valid command: stage (similar: last-grep, set, last)
       [error] Not a valid project ID: stage
       [error] Expected ':' (if selecting a configuration)
       [error] Not a valid key: stage (similar: state, target, tags)
       [error] stage
       [error]      ^
 !     Failed to build app with sbt

 !     Push rejected, failed to compile Play 2.x - Java app

**Comment by aguestuser** [comment]
@pquarme i'm hitting the same problem! what did you remove from your .gitignore?

this is mine:

```
.idea/
target/

# sbt specific
.lib/
dist/*
lib_managed/
project/boot/
project/plugins/project/

# Scala-IDE specific
.scala_dependencies
.worksheet

# borrowed from typesafe
*#
*.ipr
*.iws
*.pyc
*.tm.epoch
*.vim
*-shim.sbt
/project/plugins/project
project/boot
/logs
.cache
.classpath
.project
.settings
*.log

```
