### ISSUE TITLE
Future proof for Play

### ISSUE THREAD

**Issue by jroper** [heroku/heroku-buildpack-scala#81]
Play 2.3 now compiles/copies/processes assets in a directory structure in `target/web`.  If there are many large assets, eg images, pdfs, other files, this can significantly increase slug size with junk, since these directories aren't removed.  Also Play dumps a jar in `target` directly containing all assets (for deployment to a CDN for example).  We've seen at least one app have its slug size blow up because these new files/directories aren't removed.

So, I'd like to talk about future proofing the scala buildpack for Play.  I know very little about how build packs work for Heroku, which is why I haven't just prepared a pull request myself but wanted to talk about it first, but it seems that the following steps are done:

1. Build
2. Cache the build
3. Delete unnecessary files from the build
4. Copy the build back to where Heroku expects it

What if, for Play, the following was done:

1. Build
2. Cache the build
3. Move only `target/universal` to the place where Heroku expects it (probably also should move `target/staged` and `target/start` to maintain support for 2.0.x and 2.1.x)
4. Delete the whole build directory and ivy cache

If this was done, it would guarantee that *only* the files needed by Play are included in the slug, ensuring that anything else that Play puts in the target directory in future doesn't count, and also means that in multi project setups, where there are multiple target directories, these directories get cleaned up too.

The only place that I can think that this might cause a problem is for applications that rely on things outside of their dist artifact.  This is very bad practice, and also easy to fix, by adding the additional files that they depend on to `mappings in Universal`.  I'm not sure how/if Heroku deals with/allows breaking changes build packs, but I'm sure there are other solutions that we could come to if this stands in the way.

**Comment by jkutner** [comment]
I'm going to close this ticket, because the steps described in [this article](https://devcenter.heroku.com/articles/reducing-the-slug-size-of-play-2-x-applications) have been working really well for people. Also, Play 2.3.x and really (sbt-native-packager) has really made this less of a problem.

Thanks for the suggestions, they've definitely inspired some improvements to the buildpack.
